apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: b3o-tcc
  name: b3o-tcc-deployment
  namespace: b3o
spec:
  replicas: 3
  selector:
    matchLabels:
      app: b3o-tcc
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: b3o-tcc
    spec:
      containers:
      - image: bcorreia/go-helloworld:v0.0.2 # {"$imagepolicy": "flux-system:b3o-tcc"}
        name: go-helloworld
        env:
        - name: LOCATION
          value: "AZURE-CLOUD"
        resources:
          requests:
            cpu: "5m"
            memory: "10Mi"
          limits:
            cpu: "10m"
            memory: "20Mi"
