apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  name: b3o-tcc-ingress
  namespace: b3o
spec:
  ingressClassName: nginx
  rules:
  - host: azure.tcc.brunocorreia.me
    http:
      paths:
      - backend:
          service:
            name: b3o-tcc-service
            port:
              number: 80
        path: /
        pathType: Exact
