name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag bcorreia/go-helloworld:$(git rev-parse --short HEAD)
      
    - name: Push the Docker image
      run: docker push bcorreia/go-helloworld:$(git rev-parse --short HEAD)
