name: Docker Image CI

on:
  push:
    tags:        
      - 'v*.*.*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
  
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          
    - name: Build the Docker image
      run: docker build . --buid-arg IMAGE_VERSION=$RELEASE_VERSION -t bcorreia/go-helloworld:$RELEASE_VERSION -t bcorreia/go-helloworld:latest
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
    - name: Push the Docker image
      run: docker push bcorreia/go-helloworld:$RELEASE_VERSION && docker push bcorreia/go-helloworld:latest
